name: Release

on:
  pull_request:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run the get bump type script
        run: bash get-bump-type.sh

      - name: Create and push the release branch with the new package version
        run: |
          PACKAGE_VERSION=$(jq -r '.version' package.json)

          git checkout -b release/${PACKAGE_VERSION}

          git push origin release/${PACKAGE_VERSION}
