name: Release

on:
  pull_request:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check for changeset
        run: |
          CHANGESET_FILE=$(find .changeset -name '*.md' ! -name README.md | head -n 1)
          echo "Changeset file name: $CHANGESET_FILE"

          if [ ! -f "$CHANGESET_FILE" ]; then
            echo "No changeset found. Please create a changeset file for this PR."
            exit 1
          fi

      - name: Get change semver type from changeset and create release branch
        run: |
          CHANGESET_FILE=$(find .changeset -name '*.md' ! -name README.md | head -n 1)
          CHANGESET_LINES=$(cat "$CHANGESET_FILE")

          MAJOR=$(grep -o '"semantic-styles": major' <<< "$CHANGESET_LINES")
          MINOR=$(grep -o '"semantic-styles": minor' <<< "$CHANGESET_LINES")
          PATCH=$(grep -o '"semantic-styles": patch' <<< "$CHANGESET_LINES")

          if [ -n "$MAJOR"]; then
            npm run changeset:major

          if [ -n "$MINOR" ]; then
            npm run changeset:minor

          if [ -n "$PATCH"]; then 
            npm run changeset:patch
          fi

          if [[ "$CHANGESET_LINES" == *'semantic-styles': patch* ]]; then
            echo "Patch changeset found. Creating patch release branch."
              
          PACKAGE_VERSION=$(jq -r '.version' package.json)

          echo "Package version: $PACKAGE_VERSION"  

          git checkout -b release/${PACKAGE_VERSION}

      - name: Push release branch
        run: |
          git push origin release/${VERSION}
