name: Release

on:
  pull_request:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check for changeset
        run: |
          CHANGESET_FILE=$(find .changeset -name '*.md' ! -name README.md | head -n 1)
          echo "Changeset file name: $CHANGESET_FILE"

          if [ ! -f "$CHANGESET_FILE" ]; then
            echo "No changeset found. Please create a changeset file for this PR."
            exit 1
          fi

      - name: Create release branch
        run: |
          CHANGESET_FILE=$(find .changeset -name '*.md' ! -name README.md | head -n 1)
          CHANGESET_LINES=$(cat "$CHANGESET_FILE")

          BUMP_TYPE=$(grep -oP 'semantic-styles(.*?)\b' <<< "$CHANGESET_LINES" | head -n 1)

          echo "Bump type: ${BUMP_TYPE} ENDD"

          npm run changeset:${BUMP_TYPE}

          PACKAGE_VERSION=$(jq -r '.version' package.json)

          echo "Package version: $PACKAGE_VERSION"  

          git checkout -b release/${PACKAGE_VERSION}

      - name: Push release branch
        run: |
          git push origin release/${VERSION}
