name: Release

on:
  pull_request:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check for changeset
        run: |
          CHANGESET_FILE=$(find .changeset -name '*.md' ! -name README.md | head -n 1)
          echo "Changeset file name: $CHANGESET_FILE"

          if [ ! -f "$CHANGESET_FILE" ]; then
            echo "No changeset found. Please create a changeset file for this PR."
            exit 1
          fi

      - name: Create release branch
        run: |
          CHANGESET_FILE=$(find .changeset -name '*.md' ! -name README.md | head -n 1)
          CHANGESET_LINES=$(cat "$CHANGESET_FILE")

          CHANGESET_LINE=$CHANGESET_LINES[0]

          echo "Changeset line: $CHANGESET_LINE"

          if [[ $CHANGESET_LINE == *major* ]]; then
            echo "Major changeset found. Creating major release branch."

          if [[ $CHANGESET_LINE == *minor* ]]; then
            echo "Minor changeset found. Creating minor release branch."

          if [[ $CHANGESET_LINE == *patch* ]]; then
            echo "Patch changeset found. Creating patch release branch."
              
          PACKAGE_VERSION=$(jq -r '.version' package.json)

          echo "Package version: $PACKAGE_VERSION"  

          git checkout -b release/${PACKAGE_VERSION}

      - name: Push release branch
        run: |
          git push origin release/${VERSION}
