name: Release

on:
  pull_request:
    branches:
      - master

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run the get bump type script
        run: bash get-bump-type.sh

      - name: Create a a release PR
        run: |
          PACKAGE_VERSION=$(jq -r '.version' package.json)

          git checkout -b release/${PACKAGE_VERSION}

          git push origin release/${PACKAGE_VERSION}

          gh pr create --base release/${PACKAGE_VERSION} --t release/${PACKAGE_VERSION}
