name: Release

on:
  pull_request:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get change semver type from changeset and create release branch
        run: |
          CHANGESET_FILE=$(find .changeset -name '*.md' ! -name README.md | head -n 1)

          MAJOR=$(grep -E ': major' "$CHANGESET_FILE")
          MINOR=$(grep -E ': minor' "$CHANGESET_FILE")
          PATCH=$(grep -E ': patch' "$CHANGESET_FILE")

          if [ "$MAJOR"]; then
            echo "Major bump here"
          fi

          if [ "$MINOR" ]; then
            echo "Minor bump here"
          fi

          if [ "$PATCH"]; then
            echo "patch bump here"
          fi

          PACKAGE_VERSION=$(jq -r '.version' package.json)

          echo "version $P"

          echo "Package version $PACKAGE_VERSION"  

          git checkout -b release/${PACKAGE_VERSION}

      - name: Push release branch
        run: |
          git push origin release/${VERSION}
