name: Release

on:
  pull_request:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check for changeset
        run: |
          CHANGESET_FILE=$(find .changeset -name '*.md' ! -name README.md | head -n 1)
          echo "Changeset file name: $CHANGESET_FILE"

          if [ ! -f "$CHANGESET_FILE" ]; then
            echo "No changeset found. Please create a changeset file for this PR."
            exit 1
          fi

      - name: Create release branch
        run: |
          CHANGESET_FILE=$(find .changeset -name '*.md' ! -name README.md | head -n 1)
          CHANGESET_LINES=$(cat "$CHANGESET_FILE")

          echo "Changeset lines: ${CHANGESET_LINES} endd"

          LIB_NAME=$(grep -n "semantic-styles" "$CHANGESET_FILE" | cut -d: -f1)

          echo "Lib name: ${LIB_NAME}"

          SEMANTIC_STYLES_LINE=$(grep -n "semantic-styles" "$CHANGESET_FILE" | cut -d: -f1)

          BUMP_TYPE_LINE=$(echo "$CHANGESET_LINES[$SEMANTIC_STYLES_LINE + 1]")

          echo "Bump type line ${BUMP_TYPE_LINE}"

          BUMP_TYPE=$(echo "$BUMP_TYPE_LINE" | sed -e 's/[^a-zA-Z0-9]//g' -e 's/semanticstyles//g' -e 's/^[ \t]*//g' -e 's/[ \t]*$//g')

          echo "Bump type: ${BUMP_TYPE}"

          npm run changeset:${BUMP_TYPE}

          PACKAGE_VERSION=$(jq -r '.version' package.json)

          echo "Package version: $PACKAGE_VERSION"  

          git checkout -b release/${PACKAGE_VERSION}

      - name: Push release branch
        run: |
          git push origin release/${VERSION}
