name: Release

on:
  pull_request:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check for changeset
        run: |
          CHANGESET_FILE=$(find .changeset -name '*.md' ! -name README.md | head -n 1)
          echo "Changeset file name: $CHANGESET_FILE"

          if [ ! -f "$CHANGESET_FILE" ]; then
            echo "No changeset found. Please create a changeset file for this PR."
            exit 1
          fi

      - name: Get semver bump type
        run: |
          CHANGESET_FILE=$(find .changeset -name '*.md' ! -name README.md | head -n 1)

          CHANGESET_LINES=$(cat "$CHANGESET_FILE")

          FRONTMATTER=$(grep -n "semantic-styles" "$CHANGESET_FILE" | cut -d: -f1)

          VERSION=$(echo "$CHANGESET_LINES[$FRONTMATTER]" | cut -d" " -f3)

          echo "Semver bump type: ${BUMP_TYPE}"
          echo "Version: $VERSION"

      - name: Bump version
        run: |
          npx changeset version --bump=${BUMP_TYPE}

      - name: Create release branch
        run: |
          git checkout -b release/${VERSION}

      - name: Push release branch
        run: |
          git push origin release/${VERSION}

      - name: Delete changeset files
        run: |
          git rm -rf .changeset/*.md
          git reset HEAD .changeset/README.md
